#!/usr/bin/env python3
"""Sync images generated by IDE Gemini tool into project images/, update story.json, and rebuild contact sheet."""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from PIL import Image

from sflib.project import (
    EXIT_OK, ROOT, input_hash, load_story, save_story
)

SIZES = {"1:1": (1024, 1024), "3:4": (768, 1024), "9:16": (1080, 1920), "16:9": (1920, 1080)}


def find_brain_dirs() -> list[Path]:
    base = Path.home() / ".gemini" / "antigravity-ide" / "brain"
    try:
        if not base.is_dir():
            return []
        subdirs = [d for d in base.iterdir() if d.is_dir() and not d.name.startswith(".")]
        subdirs.sort(key=lambda d: d.stat().st_mtime, reverse=True)
        return subdirs
    except (PermissionError, OSError):
        return []


def find_candidate_file(brain_dirs: list[Path], slug: str, slide_id: str) -> Path | None:
    # slide_id e.g. "S01", "S1", "S24"
    match = re.search(r"(\d+)", slide_id)
    num = int(match.group(1)) if match else 1
    num_str = f"{num:02d}"
    single_num = str(num)
    base_slug = re.sub(r"^\d{8}(-\d{6})?-", "", slug)

    patterns = [
        re.compile(rf"{re.escape(slug)}.*s0*{single_num}[._]", re.IGNORECASE),
        re.compile(rf"{re.escape(base_slug)}.*s0*{single_num}[._]", re.IGNORECASE),
        re.compile(rf"^s0*{single_num}[._]", re.IGNORECASE),
        re.compile(rf"[._]s0*{single_num}[._]", re.IGNORECASE),
        re.compile(rf"slide[._-]?0*{single_num}[._]", re.IGNORECASE),
        re.compile(rf"s{num_str}", re.IGNORECASE),
    ]

    for brain in brain_dirs:
        candidates = []
        for file in brain.iterdir():
            if not file.is_file() or file.suffix.lower() not in [".jpg", ".jpeg", ".png", ".webp"]:
                continue
            name = file.stem
            for pat in patterns:
                if pat.search(name):
                    candidates.append((file.stat().st_mtime, file))
                    break
        if candidates:
            candidates.sort(key=lambda c: c[0], reverse=True)
            return candidates[0][1]
    return None


def sync_images(project_dir: Path, brain_dir: Path | None = None, only: set[str] | None = None) -> tuple[dict, int]:
    project_dir = project_dir if project_dir.is_absolute() else (ROOT / project_dir).resolve()
    images_dir = project_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)

    story = load_story(project_dir)
    slug = story["slug"]
    aspect = story.get("brief", {}).get("aspect", "9:16")
    target_width, target_height = SIZES.get(aspect, (1080, 1920))

    brain_dirs = [brain_dir] if brain_dir and brain_dir.is_dir() else find_brain_dirs()
    if not brain_dirs:
        return {"ok": False, "error": "No brain directory found in ~/.gemini/antigravity-ide/brain"}, 1

    synced: list[str] = []
    missing: list[str] = []

    for slide in story.get("slides", []):
        slide_id = slide["id"]
        if only and slide_id not in only:
            continue

        candidate = find_candidate_file(brain_dirs, slug, slide_id)
        if not candidate:
            missing.append(slide_id)
            continue

        target_png = images_dir / f"{slide_id}.png"
        try:
            with Image.open(candidate) as img:
                rgb_img = img.convert("RGB")
                # Resize if dimensions differ
                if rgb_img.size != (target_width, target_height):
                    # Resize while preserving high quality
                    rgb_img = rgb_img.resize((target_width, target_height), Image.Resampling.LANCZOS)
                rgb_img.save(target_png, format="PNG")
        except Exception as exc:
            missing.append(f"{slide_id} (error: {exc})")
            continue

        prompt = slide.get("visual", {}).get("prompt", "")
        seed = slide.get("image", {}).get("seed", 42)
        new_hash = input_hash({"prompt": prompt, "aspect": aspect, "provider": "gemini", "seed": seed})

        if "image" not in slide or not isinstance(slide["image"], dict):
            slide["image"] = {}

        slide["image"].update(
            path=f"images/{slide_id}.png",
            input_hash=new_hash,
            status="done",
            attempts=slide["image"].get("attempts", 0) + 1,
            last_error=None
        )
        synced.append(slide_id)

    save_story(project_dir, story)

    # Rebuild contact sheet if any synced
    if synced:
        import subprocess
        subprocess.run(["uv", "run", "scripts/sf_contact_sheet.py", str(project_dir)], capture_output=True, text=True)

    summary = {
        "ok": len(missing) == 0,
        "synced_count": len(synced),
        "synced": synced,
        "missing": missing,
        "contact_sheet": "out/contact_sheet.png" if synced else None
    }
    return summary, EXIT_OK if len(missing) == 0 else 2


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync IDE Gemini-generated images to project folder")
    parser.add_argument("project_dir", type=Path, help="Path to projects/<slug>")
    parser.add_argument("--brain-dir", type=Path, default=None, help="Explicit brain artifact directory")
    parser.add_argument("--only", default=None, help="Comma-separated slide IDs (e.g. S01,S02)")

    args = parser.parse_args()
    only = {s.strip() for s in args.only.split(",") if s.strip()} if args.only else None
    summary, code = sync_images(args.project_dir, brain_dir=args.brain_dir, only=only)
    print(json.dumps(summary, ensure_ascii=False))
    sys.exit(code)


if __name__ == "__main__":
    main()
