#!/usr/bin/env python3
"""Sync images generated by IDE Gemini tool into project images/, update story.json, and rebuild contact sheet."""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from PIL import Image

from sflib.project import (
    EXIT_OK, ROOT, input_hash, load_story, save_story
)

SIZES = {"1:1": (1024, 1024), "3:4": (768, 1024), "9:16": (1080, 1920), "16:9": (1920, 1080)}


def find_brain_dirs() -> list[Path]:
    base = Path.home() / ".gemini" / "antigravity-ide" / "brain"
    try:
        if not base.is_dir():
            return []
        subdirs = [d for d in base.iterdir() if d.is_dir() and not d.name.startswith(".")]
        subdirs.sort(key=lambda d: d.stat().st_mtime, reverse=True)
        return subdirs
    except (PermissionError, OSError):
        return []


def find_candidate_file(brain_dirs: list[Path], slug: str, slide_id: str) -> Path | None:
    # slide_id e.g. "S01", "S1", "S24"
    match = re.search(r"(\d+)", slide_id)
    num = int(match.group(1)) if match else 1
    num_str = f"{num:02d}"
    single_num = str(num)
    base_slug = re.sub(r"^\d{8}(-\d{6})?-", "", slug)
    base_slug_underscore = base_slug.replace("-", "_")
    slug_underscore = slug.replace("-", "_")

    slug_words = [w for w in base_slug.split("-") if len(w) >= 4 and w not in ["with", "from", "that"]]
    word_patterns = [re.compile(rf"{re.escape(w)}.*s0*{single_num}[._-]", re.IGNORECASE) for w in slug_words]

    patterns = [
        re.compile(rf"{re.escape(slug)}.*s0*{single_num}[._-]", re.IGNORECASE),
        re.compile(rf"{re.escape(slug_underscore)}.*s0*{single_num}[._-]", re.IGNORECASE),
        re.compile(rf"{re.escape(base_slug)}.*s0*{single_num}[._-]", re.IGNORECASE),
        re.compile(rf"{re.escape(base_slug_underscore)}.*s0*{single_num}[._-]", re.IGNORECASE),
    ] + word_patterns + [
        re.compile(rf"^s0*{single_num}[._-]", re.IGNORECASE),
        re.compile(rf"[._-]s0*{single_num}[._-]", re.IGNORECASE),
        re.compile(rf"slide[._-]?0*{single_num}[._-]", re.IGNORECASE),
        re.compile(rf"s{num_str}", re.IGNORECASE),
    ]

    for brain in brain_dirs:
        candidates = []
        for file in brain.iterdir():
            if not file.is_file() or file.suffix.lower() not in [".jpg", ".jpeg", ".png", ".webp"]:
                continue
            name = file.stem
            for prio, pat in enumerate(patterns):
                if pat.search(name):
                    candidates.append((prio, -file.stat().st_mtime, file))
                    break
        if candidates:
            candidates.sort(key=lambda c: (c[0], c[1]))
            return candidates[0][2]
    return None


def find_candidate_plate_file(brain_dirs: list[Path], slug: str, plate_key: str) -> Path | None:
    base_slug = re.sub(r"^\d{8}(-\d{6})?-", "", slug)
    clean_key = plate_key.lower().replace("-", "_")

    patterns = [
        re.compile(rf"{re.escape(slug)}.*{re.escape(clean_key)}", re.IGNORECASE),
        re.compile(rf"{re.escape(base_slug)}.*{re.escape(clean_key)}", re.IGNORECASE),
        re.compile(rf"^{re.escape(clean_key)}[._]", re.IGNORECASE),
        re.compile(rf"[._]{re.escape(clean_key)}[._]", re.IGNORECASE),
        re.compile(rf"{re.escape(clean_key)}", re.IGNORECASE),
    ]

    for brain in brain_dirs:
        candidates = []
        for file in brain.iterdir():
            if not file.is_file() or file.suffix.lower() not in [".jpg", ".jpeg", ".png", ".webp"]:
                continue
            name = file.stem.lower()
            for pat in patterns:
                if pat.search(name):
                    candidates.append((file.stat().st_mtime, file))
                    break
        if candidates:
            candidates.sort(key=lambda c: c[0], reverse=True)
            return candidates[0][1]
    return None


def sync_images(project_dir: Path, brain_dir: Path | None = None, only: set[str] | None = None) -> tuple[dict, int]:
    project_dir = project_dir if project_dir.is_absolute() else (ROOT / project_dir).resolve()
    images_dir = project_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)
    plates_dir = project_dir / "plates"
    plates_dir.mkdir(parents=True, exist_ok=True)

    story = load_story(project_dir)
    slug = story["slug"]
    aspect = story.get("brief", {}).get("aspect", "9:16")
    target_width, target_height = SIZES.get(aspect, (1080, 1920))

    brain_dirs = [brain_dir] if brain_dir and brain_dir.is_dir() else find_brain_dirs()
    if not brain_dirs:
        return {"ok": False, "error": "No brain directory found in ~/.gemini/antigravity-ide/brain"}, 1

    synced: list[str] = []
    missing: list[str] = []

    # 1. Sync Cast Plates
    for member in story.get("cast", []):
        member_id = member.get("id")
        plates = member.get("plates")
        if plates and isinstance(plates, dict):
            for kind in ["face", "half", "full"]:
                plate_key = f"{member_id}_{kind}"
                if only and plate_key not in only:
                    continue
                candidate = find_candidate_plate_file(brain_dirs, slug, plate_key)
                if candidate:
                    plate_aspect = "1:1" if kind == "face" else ("3:4" if kind == "half" else "9:16")
                    pw, ph = SIZES.get(plate_aspect, (1024, 1024))
                    target_plate = plates_dir / f"{plate_key}.png"
                    try:
                        with Image.open(candidate) as img:
                            rgb_img = img.convert("RGB")
                            if rgb_img.size != (pw, ph):
                                rgb_img = rgb_img.resize((pw, ph), Image.Resampling.LANCZOS)
                            rgb_img.save(target_plate, format="PNG")
                        p_hash = input_hash({"prompt": plates[kind].get("prompt", ""), "aspect": plate_aspect, "provider": "gemini"})
                        plates[kind].update(
                            path=f"plates/{plate_key}.png",
                            input_hash=p_hash,
                            status="done",
                            attempts=plates[kind].get("attempts", 0) + 1,
                            last_error=None
                        )
                        synced.append(plate_key)
                    except Exception as exc:
                        if only and plate_key in only:
                            missing.append(f"{plate_key} (error: {exc})")
                elif only and plate_key in only:
                    missing.append(plate_key)

    # 2. Sync Location Plates
    for loc in story.get("locations", []):
        loc_id = loc.get("id")
        plate_key = loc_id
        if only and plate_key not in only and f"{plate_key}_master" not in only:
            continue
        plate = loc.get("plate")
        if plate and isinstance(plate, dict):
            candidate = find_candidate_plate_file(brain_dirs, slug, plate_key) or find_candidate_plate_file(brain_dirs, slug, f"{plate_key}_master")
            if candidate:
                target_plate = plates_dir / f"{plate_key}.png"
                try:
                    with Image.open(candidate) as img:
                        rgb_img = img.convert("RGB")
                        if rgb_img.size != (target_width, target_height):
                            rgb_img = rgb_img.resize((target_width, target_height), Image.Resampling.LANCZOS)
                        rgb_img.save(target_plate, format="PNG")
                    p_hash = input_hash({"prompt": plate.get("prompt", ""), "aspect": aspect, "provider": "gemini"})
                    plate.update(
                        path=f"plates/{plate_key}.png",
                        input_hash=p_hash,
                        status="done",
                        attempts=plate.get("attempts", 0) + 1,
                        last_error=None
                    )
                    synced.append(plate_key)
                except Exception as exc:
                    if only and (plate_key in only or f"{plate_key}_master" in only):
                        missing.append(f"{plate_key} (error: {exc})")
            elif only and (plate_key in only or f"{plate_key}_master" in only):
                missing.append(plate_key)

    # 3. Sync Slides
    for slide in story.get("slides", []):
        slide_id = slide["id"]
        if only and slide_id not in only:
            continue

        candidate = find_candidate_file(brain_dirs, slug, slide_id)
        if not candidate:
            missing.append(slide_id)
            continue

        target_png = images_dir / f"{slide_id}.png"
        try:
            with Image.open(candidate) as img:
                rgb_img = img.convert("RGB")
                # Resize if dimensions differ
                if rgb_img.size != (target_width, target_height):
                    # Resize while preserving high quality
                    rgb_img = rgb_img.resize((target_width, target_height), Image.Resampling.LANCZOS)
                rgb_img.save(target_png, format="PNG")
        except Exception as exc:
            missing.append(f"{slide_id} (error: {exc})")
            continue

        prompt = slide.get("visual", {}).get("prompt", "")
        seed = slide.get("image", {}).get("seed", 42)
        new_hash = input_hash({"prompt": prompt, "aspect": aspect, "provider": "gemini", "seed": seed})

        if "image" not in slide or not isinstance(slide["image"], dict):
            slide["image"] = {}

        slide["image"].update(
            path=f"images/{slide_id}.png",
            input_hash=new_hash,
            status="done",
            attempts=slide["image"].get("attempts", 0) + 1,
            last_error=None
        )
        synced.append(slide_id)

    save_story(project_dir, story)

    # Rebuild contact sheet if any synced
    if synced:
        import subprocess
        subprocess.run(["uv", "run", "scripts/sf_contact_sheet.py", str(project_dir)], capture_output=True, text=True)

    summary = {
        "ok": len(missing) == 0,
        "synced_count": len(synced),
        "synced": synced,
        "missing": missing,
        "contact_sheet": "out/contact_sheet.png" if synced else None
    }
    return summary, EXIT_OK if len(missing) == 0 else 2


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync IDE Gemini-generated images to project folder")
    parser.add_argument("project_dir", type=Path, help="Path to projects/<slug>")
    parser.add_argument("--brain-dir", type=Path, default=None, help="Explicit brain artifact directory")
    parser.add_argument("--only", default=None, help="Comma-separated slide IDs (e.g. S01,S02)")

    args = parser.parse_args()
    only = {s.strip() for s in args.only.split(",") if s.strip()} if args.only else None
    summary, code = sync_images(args.project_dir, brain_dir=args.brain_dir, only=only)
    print(json.dumps(summary, ensure_ascii=False))
    sys.exit(code)


if __name__ == "__main__":
    main()
